apiVersion: v1
kind: Service
metadata:
  name: forklol-api-service-beta
  labels:
    app: forklol-api-beta
    tier: forklol-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: forklol-api-beta
    tier: forklol-backend