apiVersion: v1
kind: Service
metadata:
  name: forklol-api-service
  labels:
    app: forklol-api
    tier: forklol-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: forklol-api
    tier: forklol-backend